name: finalexam
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-282.1.beta

# Add regular dependencies here.
dependencies:
  web: ^0.5.1
  dio: ^5.0.0
  universal_io: ^2.2.2

assets:
    - assets/data.json 

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0
